/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package koneksidb;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class FormUploadSkripsi extends javax.swing.JFrame {

    Connection conn = koneksi.getConnection();
    File fileTerpilih = null;
    public FormUploadSkripsi() {
        initComponents();
        tampilkanDokumen();
    }
    
    public void tampilkanDokumen() {
    String nim = txtNIM.getText().trim();
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Nama File");
    model.addColumn("Tanggal Upload");

    try {
        String sql = "SELECT nama_file, tanggal_upload FROM dokumen_skripsi WHERE id_mahasiswa = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, nim);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("nama_file"),
                rs.getDate("tanggal_upload")
            });
        }

        tabelDokumen.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan dokumen: " + e.getMessage());
    }
}
public void simpanUmpanBalik(String nim, String jenis, String pesan) {
    try {
        String sql = "INSERT INTO umpan_balik (id_mahasiswa, jenis, pesan) VALUES (?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, nim);
        ps.setString(2, jenis);
        ps.setString(3, pesan);
        ps.executeUpdate();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal simpan umpan balik: " + e.getMessage());
    }
}

        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDokumen = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        txtNIM = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFileInfo = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Pilih");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tabelDokumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelDokumen);

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtNIM.setText("jTextField1");

        txtFileInfo.setColumns(20);
        txtFileInfo.setRows(5);
        jScrollPane2.setViewportView(txtFileInfo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
    int returnVal = chooser.showOpenDialog(this);

    if (returnVal == JFileChooser.APPROVE_OPTION) {
        fileTerpilih = chooser.getSelectedFile();
        txtFileInfo.setText("Nama File: " + fileTerpilih.getName() +
                            "\nLokasi: " + fileTerpilih.getAbsolutePath());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String nim = txtNIM.getText().trim();

    if (fileTerpilih == null || nim.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Isi NIM dan pilih file terlebih dahulu!");
        return;
    }

    try {
        // Buat folder uploads jika belum ada
        File folder = new File("uploads");
        if (!folder.exists()) {
            folder.mkdir();
        }

        // Salin file ke folder uploads
        String namaFile = fileTerpilih.getName();
        File tujuan = new File("uploads/" + namaFile);
        Files.copy(fileTerpilih.toPath(), tujuan.toPath(), StandardCopyOption.REPLACE_EXISTING);

        // Simpan info ke database
        String sql = "INSERT INTO dokumen_skripsi (id_mahasiswa, nama_file, path_file) VALUES (?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, nim);
        ps.setString(2, namaFile);
        ps.setString(3, tujuan.getPath());
        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Dokumen berhasil diupload!");
        tampilkanDokumen();
        txtFileInfo.setText("");
        fileTerpilih = null;

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal upload: " + e.getMessage());
    }

    
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int baris = tabelDokumen.getSelectedRow();
    String nim = txtNIM.getText().trim();

    if (baris == -1 || nim.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Pilih dokumen dan isi NIM terlebih dahulu!");
        return;
    }

    int konfirmasi = JOptionPane.showConfirmDialog(
        this, "Hapus dokumen ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            String namaFile = tabelDokumen.getValueAt(baris, 0).toString();

            // Ambil path file
            String path = "";
            String sqlPath = "SELECT path_file FROM dokumen_skripsi WHERE nama_file = ? AND id_mahasiswa = ?";
            PreparedStatement psCari = conn.prepareStatement(sqlPath);
            psCari.setString(1, namaFile);
            psCari.setString(2, nim);
            ResultSet rs = psCari.executeQuery();

            if (rs.next()) {
                path = rs.getString("path_file");
            }

            // Hapus file fisik
            File file = new File(path);
            if (file.exists()) {
                file.delete();
            }

            // Hapus dari database
            String sqlHapus = "DELETE FROM dokumen_skripsi WHERE nama_file = ? AND id_mahasiswa = ?";
            PreparedStatement psHapus = conn.prepareStatement(sqlHapus);
            psHapus.setString(1, namaFile);
            psHapus.setString(2, nim);
            psHapus.executeUpdate();

            JOptionPane.showMessageDialog(null, "Dokumen berhasil dihapus.");
            tampilkanDokumen();
            txtFileInfo.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal hapus dokumen: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUploadSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUploadSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUploadSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUploadSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUploadSkripsi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelDokumen;
    private javax.swing.JTextArea txtFileInfo;
    private javax.swing.JTextField txtNIM;
    // End of variables declaration//GEN-END:variables
}
